model:
  seq_len: 192
  vocab_size: 10000
  d_ffn: 1024
  d_model: 256
  n_heads: 8
  drop_rate: 0.1
  n_layers: 4

tokenizer:
  min_freq: 5
  standardize: "lower"
  pattern_tokenize: True

training:
  data_limit: 100000
  seed: 42
  batch_size: 32
  buffer_size: 10000
  epochs: 20
  val_split: 0.1
  weight_decay: 0.0001
  warmup_steps: 4000
  save: True

inference:
  max_len: 96
  temperature: 0.8
  top_p: 0.9

path:
  dataset: "project/data/001_dataset.jsonl"
  tokenizer: "project/artifacts/vocab.json"
  model: "project/artifacts/model.keras"
